<?php

namespace Database\Seeders\Organization\OrganizationChart;

use App\Models\Organization\OrganizationChart\OrganizationChart;
use Illuminate\Database\Seeder;

class OrganizationChartSeeder extends Seeder
{
    public function run(): void
    {
        OrganizationChart::create(['acronym' => 'SMS', 'title' => 'Secretaria Municipal de Saúde', 'filter' => 'secretaria municipal de saude', 'order' => '0SMS', 'hierarchy' => 0, 'number_hierarchy' => 1]);
        OrganizationChart::create(['acronym' => 'AUD', 'title' => 'Auditoria', 'filter' => 'auditoria', 'order' => '0SMS2AUD', 'hierarchy' => 1, 'number_hierarchy' => 2]);
        OrganizationChart::create(['acronym' => 'CMS', 'title' => 'Conselho Municipal de Saúde', 'filter' => 'conselho municipal de saude', 'order' => '0SMS3CMS', 'hierarchy' => 1, 'number_hierarchy' => 2]);
        OrganizationChart::create(['acronym' => 'SEABVS', 'title' => 'Secretaria Executiva de Atenção Básica e Vigilância em Saúde', 'filter' => 'secretaria executiva de atencao basica e vigilancia em saude', 'order' => '0SMS4SEABVS', 'hierarchy' => 1, 'number_hierarchy' => 2]);
        OrganizationChart::create(['acronym' => 'GGAB', 'title' => 'Gerência Geral da Atenção Básica', 'filter' => 'gerencia geral da atencao basica', 'order' => '0SMS4SEABVS5GGAB', 'hierarchy' => 4, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'GMPA', 'title' => 'Gerência de Monitoramento do Planifica e Apoio institucional', 'filter' => 'gerencia de monitoramento do planifica e apoio institucional', 'order' => '0SMS4SEABVS5GGAB6GMPA', 'hierarchy' => 5, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CPNI', 'title' => 'Coordenação PNI', 'filter' => 'coordenacao pni', 'order' => '0SMS4SEABVS5GGAB7CPNI', 'hierarchy' => 5, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GPE', 'title' => 'Gerência de Políticas Estratégicas', 'filter' => 'gerencia de politicas estrategicas', 'order' => '0SMS4SEABVS5GGAB8GPE', 'hierarchy' => 5, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CN', 'title' => 'Coordenação de Nutrição', 'filter' => 'coordenacao de nutricao', 'order' => '0SMS4SEABVS5GGAB8GPE9CN', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CPE', 'title' => 'Coordenação de Políticas Estratégicas', 'filter' => 'coordenacao de politicas estrategicas', 'order' => '0SMS4SEABVS5GGAB8GPE10CPE', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CPSEM', 'title' => 'Coordenação de Promoção a Saúde e eMulti', 'filter' => 'coordenacao de promocao a saude e emulti', 'order' => '0SMS4SEABVS5GGAB8GPE11CPSEM', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CPSESAD', 'title' => 'Coordenação do PSE e SAD', 'filter' => 'coordenacao do pse e sad', 'order' => '0SMS4SEABVS5GGAB8GPE12CPSESAD', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CSB', 'title' => 'Coordenação de Saúde Bucal', 'filter' => 'coordenacao de saude bucal', 'order' => '0SMS4SEABVS5GGAB8GPE13CSB', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CSC', 'title' => 'Coordenação de Saúde da Criança', 'filter' => 'coordenacao de saude da crianca', 'order' => '0SMS4SEABVS5GGAB8GPE14CSC', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CSM', 'title' => 'Coordenação de Saúde da Mulher', 'filter' => 'coordenacao de saude da mulher', 'order' => '0SMS4SEABVS5GGAB8GPE15CSM', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CSPD', 'title' => 'Coordenação de Saúde da Pessoa com Deficiência', 'filter' => 'coordenacao de saude da pessoa com deficiencia', 'order' => '0SMS4SEABVS5GGAB8GPE16CSPD', 'hierarchy' => 8, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'SIGAB', 'title' => 'Sistema de Informação Gerência de Atenção Básica', 'filter' => 'sistema de informacao gerencia de atencao basica', 'order' => '0SMS4SEABVS5GGAB17SIGAB', 'hierarchy' => 5, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GPP', 'title' => 'Gerência de Politicas e Programas da APS', 'filter' => 'gerencia de politicas e programas da aps', 'order' => '0SMS4SEABVS5GGAB18GPP', 'hierarchy' => 5, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GGVS', 'title' => 'Gerência Geral de Vigilância em Saúde', 'filter' => 'gerencia geral de vigilancia em saude', 'order' => '0SMS4SEABVS19GGVS', 'hierarchy' => 4, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'CEREST', 'title' => 'Centro de Referência em Saúde do Trabalhador', 'filter' => 'centro de referencia em saude do trabalhador', 'order' => '0SMS4SEABVS19GGVS20CEREST', 'hierarchy' => 19, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GEPID', 'title' => 'Gerência de Vigilância Epidemiológica', 'filter' => 'gerencia de vigilancia epidemiologica', 'order' => '0SMS4SEABVS19GGVS21GEPID', 'hierarchy' => 19, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CDTN', 'title' => 'Coordenação de Doenças Tropicais e Negligenciadas', 'filter' => 'coordenacao de doencas tropicais e negligenciadas', 'order' => '0SMS4SEABVS19GGVS21GEPID22CDTN', 'hierarchy' => 21, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CISTA', 'title' => 'Coordenação IST/AIDS e Doenças Imunopreviníveis', 'filter' => 'coordenacao ist/aids e doencas imunopreviniveis', 'order' => '0SMS4SEABVS19GGVS21GEPID23CISTA', 'hierarchy' => 21, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CSS', 'title' => 'Cordenação SIM/SINASC', 'filter' => 'cordenacao sim/sinasc', 'order' => '0SMS4SEABVS19GGVS21GEPID24CSS', 'hierarchy' => 21, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CVAI', 'title' => 'Coordenação de Violência Autoprovada e Interpessoal', 'filter' => 'coordenacao de violencia autoprovada e interpessoal', 'order' => '0SMS4SEABVS19GGVS21GEPID25CVAI', 'hierarchy' => 21, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'CVEH', 'title' => 'Coordenação de Vigilância Epidemiológica Hospitalar', 'filter' => 'coordenacao de vigilancia epidemiologica hospitalar', 'order' => '0SMS4SEABVS19GGVS21GEPID26CVEH', 'hierarchy' => 21, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'GEVAM', 'title' => 'Gerência de Vigilância Ambiental', 'filter' => 'gerencia de vigilancia ambiental', 'order' => '0SMS4SEABVS19GGVS27GEVAM', 'hierarchy' => 19, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CARB', 'title' => 'Coordenação Arboviroses', 'filter' => 'coordenacao arboviroses', 'order' => '0SMS4SEABVS19GGVS27GEVAM28CARB', 'hierarchy' => 27, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'VISAT', 'title' => 'Vigilância em Saúde do Trabalhador e da Trabalhadora', 'filter' => 'vigilancia em saude do trabalhador e da trabalhadora', 'order' => '0SMS4SEABVS19GGVS27GEVAM29VISAT', 'hierarchy' => 27, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'COVISA', 'title' => 'Coordenação de Vigilância Sanitária', 'filter' => 'coordenacao de vigilancia sanitaria', 'order' => '0SMS4SEABVS19GGVS30GEVISA31COVISA', 'hierarchy' => 30, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'SEPAF', 'title' => 'Secretaria Executiva de Planejamento Administração e Finanças', 'filter' => 'secretaria executiva de planejamento administracao e financas', 'order' => '0SMS32SEPAF', 'hierarchy' => 1, 'number_hierarchy' => 2]);
        OrganizationChart::create(['acronym' => 'CPPAD', 'title' => 'Comissão Permanente de Processo Administrativo Disciplinar', 'filter' => 'comissao permanente de processo administrativo disciplinar', 'order' => '0SMS32SEPAF33CPPAD', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'FMS', 'title' => 'Fundo Municipal de Saúde', 'filter' => 'fundo municipal de saude', 'order' => '0SMS32SEPAF34FMS', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'GASF', 'title' => 'Gerência de Assistência Farmacêutica', 'filter' => 'gerencia de assistencia farmaceutica', 'order' => '0SMS32SEPAF35GASF', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'CCAF', 'title' => 'Coordenação da assistência farmacêutica', 'filter' => 'coordenacao da assistencia farmaceutica', 'order' => '0SMS32SEPAF35GASF36CCAF', 'hierarchy' => 34, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GGG', 'title' => 'Gerência Geral de Gestão', 'filter' => 'gerencia geral de gestao', 'order' => '0SMS32SEPAF37GGG', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'CCOMP', 'title' => 'Coordenação de Compras', 'filter' => 'coordenacao de compras', 'order' => '0SMS32SEPAF37GGG38CCOMP', 'hierarchy' => 36, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CEC', 'title' => 'Coordenação de Engenharia Clínica', 'filter' => 'coordenacao de engenharia clinica', 'order' => '0SMS32SEPAF37GGG39CEC', 'hierarchy' => 36, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CNEM', 'title' => 'Coordenação do Núcleo de Engenharia e Manutenção', 'filter' => 'coordenacao do nucleo de engenharia e manutencao', 'order' => '0SMS32SEPAF37GGG40CNEM', 'hierarchy' => 36, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'COAF', 'title' => 'Coordenação Administrativa Financeira', 'filter' => 'coordenacao administrativa financeira', 'order' => '0SMS32SEPAF37GGG41COAF', 'hierarchy' => 36, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GADPEGDC', 'title' => 'Gerência de ADP e GDC', 'filter' => 'gerencia de adp e gdc', 'order' => '0SMS32SEPAF42GADPEGDC', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'ADP', 'title' => 'Análise de Processos', 'filter' => 'analise de processos', 'order' => '0SMS32SEPAF42GADPEGDC43ADP', 'hierarchy' => 41, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GDC', 'title' => 'Gestão de Contratos', 'filter' => 'gestao de contratos', 'order' => '0SMS32SEPAF42GADPEGDC44GDC', 'hierarchy' => 41, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CDA', 'title' => 'Coodenação de Almoxarifado', 'filter' => 'coodenacao de almoxarifado', 'order' => '0SMS32SEPAF37GGG45CDA', 'hierarchy' => 36, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GGT', 'title' => 'Gerência de Gestão do Trabalho', 'filter' => 'gerencia de gestao do trabalho', 'order' => '0SMS32SEPAF46GGT', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'CFP', 'title' => 'Coordenação de Folha de Pagamento', 'filter' => 'coordenacao de folha de pagamento', 'order' => '0SMS32SEPAF46GGT47CFP', 'hierarchy' => 45, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CGT', 'title' => 'Coordenação de Gestão do Trabalho', 'filter' => 'coordenacao de gestao do trabalho', 'order' => '0SMS32SEPAF46GGT48CGT', 'hierarchy' => 45, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GNEP', 'title' => 'Gerência do Núcleo de Educação Permanente', 'filter' => 'gerencia do nucleo de educacao permanente', 'order' => '0SMS49GNEP', 'hierarchy' => 1, 'number_hierarchy' => 2]);
        OrganizationChart::create(['acronym' => 'GTI', 'title' => 'Gerencia de Tecnologia da Informação e Comunicação', 'filter' => 'gerencia de tecnologia da informacao e comunicacao', 'order' => '0SMS32SEPAF50GTI', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'GPLAS', 'title' => 'Gerencia de Planejamento em Saúde', 'filter' => 'gerencia de planejamento em saude', 'order' => '0SMS32SEPAF51GPLAS', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'UC', 'title' => 'Unidade de Contratação (CPL)', 'filter' => 'unidade de contratacao (cpl)', 'order' => '0SMS32SEPAF52UC', 'hierarchy' => 31, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'SERAE', 'title' => 'Secretaria Executiva de Regulação e Atenção Especializada', 'filter' => 'secretaria executiva de regulacao e atencao especializada', 'order' => '0SMS53SERAE', 'hierarchy' => 1, 'number_hierarchy' => 2]);
        OrganizationChart::create(['acronym' => 'GGAE', 'title' => 'Gerência Geral de Atenção Especializada', 'filter' => 'gerencia geral de atencao especializada', 'order' => '0SMS53SERAE54GGAE', 'hierarchy' => 52, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'CAMB', 'title' => 'Coordenação Ambulatórios', 'filter' => 'coordenacao ambulatorios', 'order' => '0SMS53SERAE54GGAE55CAMB', 'hierarchy' => 53, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CHOSP', 'title' => 'Coordenação Hospitalar', 'filter' => 'coordenacao hospitalar', 'order' => '0SMS53SERAE54GGAE56CHOSP', 'hierarchy' => 53, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CRSM', 'title' => 'Coordenação de Saúde Mental', 'filter' => 'coordenacao de saude mental', 'order' => '0SMS53SERAE54GGAE57CRSM', 'hierarchy' => 53, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'GURG', 'title' => 'Gerência de Urgência e Emergência', 'filter' => 'gerencia de urgencia e emergencia', 'order' => '0SMS53SERAE54GGAE58GURG', 'hierarchy' => 53, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'SAMU', 'title' => 'SAMU Caruaru', 'filter' => 'samu caruaru', 'order' => '0SMS53SERAE54GGAE58GURG59SAMU', 'hierarchy' => 57, 'number_hierarchy' => 5]);
        OrganizationChart::create(['acronym' => 'GRAC', 'title' => 'Gerência de Regulação Avaliação e Controle', 'filter' => 'gerencia de regulacao avaliacao e controle', 'order' => '0SMS53SERAE60GRAC', 'hierarchy' => 52, 'number_hierarchy' => 3]);
        OrganizationChart::create(['acronym' => 'CAC', 'title' => 'Coordenação de Avaliação e Controle', 'filter' => 'coordenacao de avaliacao e controle', 'order' => '0SMS53SERAE60GRAC61CAC', 'hierarchy' => 59, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CFA', 'title' => 'Coordenação de Fluxos Assistenciais', 'filter' => 'coordenacao de fluxos assistenciais', 'order' => '0SMS53SERAE60GRAC62CFA', 'hierarchy' => 59, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CNES', 'title' => 'Cadastro Nacional de Estabelecimentos de Saúde', 'filter' => 'cadastro nacional de estabelecimentos de saude', 'order' => '0SMS53SERAE60GRAC63CNES', 'hierarchy' => 59, 'number_hierarchy' => 4]);
        OrganizationChart::create(['acronym' => 'CNGR', 'title' => 'Coordenação do Núcleo de Gestão de Regulação', 'filter' => 'coordenacao do nucleo de gestao de regulacao', 'order' => '0SMS53SERAE60GRAC64CNGR', 'hierarchy' => 59, 'number_hierarchy' => 4]);
    }
}
